spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud-demo?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: huawei123

management:
  security:
    enabled: false

endpoints:
  logfile:
    enabled: true

security:
  oauth2:
    resource:
      id: gateway-service