spring:
  application:
    name: service-auth

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev?useUnicode=true&characterEncoding=utf8&characterSetResults=utf-8
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: 192.168.43.159
    port: 6379
    database: 1

server:
  port: 9098

eureka:
  client:
    serviceUrl:
      serviceZone: http://localhost:8761/eureka/