server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/qmyll/xmall.git
          searchPaths: repo-config
          username:
          password:
      label: master